spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
datasource:
  google:
    connection:
      # these are defined by google
      rootFolder: root
      connectionJson: src/main/resources/mySecrets.json
storage:
  google: true
